name: Xgtd

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Cache paths
      uses: actions/cache@v2
      with:
        path: |
          ~/.ccache
          ~/.cache/ccache
        key: ${{matrix.os}}-ccache
    - name: Install build dependencies (Ubuntu)
      run: sudo apt update && sudo apt install -y 
        autoconf
        automake
        cmake
        g++
        libssl-dev
        libtool
        make
        pkg-config
        python3
        python3-jinja2
        scrypt
        dnsutils
        ccache
        libboost-all-dev
        build-essential
        curl
        zlib1g-dev
        libreadline-dev
        libyaml-dev
        libxml2-dev
        libxslt-dev
        ninja-build
      if: startsWith(matrix.os, 'ubuntu')
    - name: Install build dependencies (macOS)
      run: brew install
        autoconf
        automake
        cmake
        boost
        icu4c
        libtool
        openssl
        zlib
        bzip2
        ccache
        python3
        ninja && python3 -m pip install jinja2
      if: startsWith(matrix.os, 'macOS')
    - name: Configure cmake (Ubuntu)
      run: cmake -D CMAKE_BUILD_TYPE=Debug -G Ninja -B build -S .
      if: startsWith(matrix.os, 'ubuntu')
    - name: Configure cmake (macOS)
      run: CMAKE_PREFIX_PATH=/usr/local/opt/openssl@1.1 cmake -D CMAKE_BUILD_TYPE=Debug -G Ninja -B build -S .
      if: startsWith(matrix.os, 'macOS')
    - name: Build xgtd
      run: ninja -C build xgtd